<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'a295e5a056fe797c0e97482c60611c5f' => $baseDir . '/config.php',
);
